### ISSUE TITLE
Failed to create OCP artifact

### ISSUE THREAD

**Issue by fwmarkcheung** [OpenShiftDemos/containerizing-apps-2021#4]
I tried to create a pod following the instructions in lab, but got weird error.  Here are the details:

[lab-user@studentvm 0 ~/workspace/mariadb/openshift]$ ls -l
total 4
-rw-r--r--. 1 lab-user users 392 Sep 24 18:49 mariadb-pod.yaml
[lab-user@studentvm 0 ~/workspace/mariadb/openshift]$ id
uid=1001(lab-user) gid=100(users) groups=100(users),10(wheel) context=unconfined_u:uncon
fined_r:unconfined_t:s0-s0:c0.c1023
[lab-user@studentvm 0 ~/workspace/mariadb/openshift]$ oc create -f mariadb-pod.yaml
error: unable to recognize "mariadb-pod.yaml": Unauthorized
[lab-user@studentvm 1 ~/workspace/mariadb/openshift]$

The file is there and it seems to have the right privilege, but I got the error:

error: unable to recognize "mariadb-pod.yaml": Unauthorized

From the prompt, it looks like it switch between vms?  It changed from [lab-user@studentvm 0] to [lab-user@studentvm 1]?

**Comment by thoraxe** [comment]
IIRC your prompt includes an error code. Since `oc create` failed, it's showing you the bash exit/error code, which was `1`. If you do `ls` it will likely switch back to zero.

Are you sure that the `Unauthorized` is coming from `bash` and not from `oc`? My guess is you have either been logged out (inactivity) or did not `oc login` to the cluster.

**Comment by fwmarkcheung** [comment]
That could be case.

thx!
